apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lens-service-summary.fullname" . }}
  labels:
    {{- include "lens-service-summary.labels" . | nindent 4 }}
data:
  FHIR_EPI_URL: {{ .Values.config.fhirEpiUrl | quote }}
  FHIR_IPS_URL: {{ .Values.config.fhirIpsUrl | quote }}
  MODEL_URL: {{ .Values.config.modelUrl | quote }}
