apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lens-service-summary.fullname" . }}
  labels:
    {{- include "lens-service-summary.labels" . | nindent 4 }}
type: Opaque
stringData:
  OPENAI_KEY: {{ .Values.secret.openaiKey | quote }}
  GROQ_API_KEY: {{ .Values.secret.groqApiKey | quote }}
